---
title: "Untitled"
author: "Binish Kurian Chandy"
date: "4/13/2018"
output: html_document
---

```{r setup, include=FALSE}
library('tm')
library('ggplot2')
knitr::opts_chunk$set(echo = TRUE)
```

### Define location for training and test dataset
```{r}
spam.path <- "data/spam/"
easyham.path <- "data/easy_ham/"
easyham.test.path <- "data/easy_ham_test/"
```

### Create a vector of spam emails for processing
```{r}
get.msg <- function(path) {
        con <- file(path, open = "rt", encoding = "latin1")
        text <- readLines(con)
        msg <- text[seq(which(text == "")[1] + 1, length(text), 1)]
        close(con)
        return(paste(msg, collapse = "\n"))
}

spam.docs <- dir(spam.path)
spam.docs <- spam.docs[which(spam.docs != "cmds")]
all.spam <- sapply(spam.docs,
                   function(p) get.msg(file.path(spam.path, p)))

head(all.spam, n = 1)
```

### Create text corpus and term document matrix(TDM) from spam email vector
```{r}
get.tdm <- function(doc.vec) {
        control <- list(stopwords = TRUE,
                        removePunctuation = TRUE,
                        removeNumbers = TRUE,
                        minDocFreq = 2)
        doc.corpus <- Corpus(VectorSource(doc.vec))
        doc.dtm <- TermDocumentMatrix(doc.corpus, control)
        return(doc.dtm)
}

spam.tdm <- get.tdm(all.spam)
```

### Create a data frame that provides the feature set from the training SPAM data
```{r}
spam.matrix <- as.matrix(spam.tdm)
spam.counts <- rowSums(spam.matrix)
spam.df <- data.frame(cbind(names(spam.counts),
                            as.numeric(spam.counts)),
                      stringsAsFactors = FALSE)
names(spam.df) <- c("term", "frequency")
spam.df$frequency <- as.numeric(spam.df$frequency)
spam.occurrence <- sapply(1:nrow(spam.matrix),
                          function(i)
                          {
                                  length(which(spam.matrix[i, ] > 0)) / ncol(spam.matrix)
                          })
spam.density <- spam.df$frequency / sum(spam.df$frequency)

spam.df <- transform(spam.df,
                     density = spam.density,
                     occurrence = spam.occurrence)

head(spam.df[with(spam.df, order(-occurrence)),])
```

### Process ham training data set using above steps
```{r}
easyham.docs <- dir(easyham.path)
easyham.docs <- easyham.docs[which(easyham.docs != "cmds")]
all.easyham <- sapply(easyham.docs[1:length(spam.docs)],
                      function(p) get.msg(file.path(easyham.path, p)))

easyham.tdm <- get.tdm(all.easyham)

easyham.matrix <- as.matrix(easyham.tdm)
easyham.counts <- rowSums(easyham.matrix)
easyham.df <- data.frame(cbind(names(easyham.counts),
                               as.numeric(easyham.counts)),
                         stringsAsFactors = FALSE)
names(easyham.df) <- c("term", "frequency")
easyham.df$frequency <- as.numeric(easyham.df$frequency)
easyham.occurrence <- sapply(1:nrow(easyham.matrix),
                             function(i)
                             {
                                     length(which(easyham.matrix[i, ] > 0)) / ncol(easyham.matrix)
                             })
easyham.density <- easyham.df$frequency / sum(easyham.df$frequency)

easyham.df <- transform(easyham.df,
                        density = easyham.density,
                        occurrence = easyham.occurrence)
head(easyham.df[with(easyham.df, order(-occurrence)),])
```

### Apply naive Bayes classifier on test dataset
```{r}
classify.email <- function(path, training.df, prior = 0.5, c = 1e-6) {
        msg <- get.msg(path)
        msg.tdm <- get.tdm(msg)
        msg.freq <- rowSums(as.matrix(msg.tdm))
        msg.match <- intersect(names(msg.freq), training.df$term)
        if(length(msg.match) < 1)
        {
                return(prior * c ^ (length(msg.freq)))
        }
        else
        {
                match.probs <- training.df$occurrence[match(msg.match, training.df$term)]
                return(prior * prod(match.probs) * c ^ (length(msg.freq) - length(msg.match)))
        }
}

easyham.test.docs <- dir(easyham.test.path)
easyham.test.docs <- easyham.test.docs[which(easyham.test.docs != "cmds")]

easyham.test.spamtest <- sapply(easyham.test.docs,
                           function(p) classify.email(file.path(easyham.test.path, p), training.df = spam.df, prior = 0.2))

easyham.test.hamtest <- sapply(easyham.test.docs,
                          function(p) classify.email(file.path(easyham.test.path, p), training.df = easyham.df, prior = 0.8))

easyham.test.res <- ifelse(easyham.test.spamtest > easyham.test.hamtest,
                      TRUE,
                      FALSE)
summary(easyham.test.res)
```

### Conclusion
```
The naive Bayes classifier is able to classify spam vs ham emails with around
97.7% accuracy.
```

### References
```
Automated Data Collection with R  
Machine Learning for Hackers
```




